site_name: MkDocs Starter
theme:
  name: material
  features: 
    - content.code.annotate
    - content.action.edit
    #- navigation.instant #Disabled so repository information is being updated on every click
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes #to be review
    - navigation.path
    - toc.integrate
    - toc.follow


edit_uri: edit/main/docs/
repo_url: https://github.com/boozallen/mkdocs-yamp-plugin

markdown_extensions:
  - admonition
  - abbr
  - footnotes
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: "docs"
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search: {}
  - my_mkdocs_plugin
  - monorepo
  - editurl



extra_css:
 - css/extra.css #to be review

extra: #to be review
  generator: false
  version:
    provider: mike
    default: latest
  repo_config_path: 'repo_config.json'

# Page Tree
nav:
  - Home: 
    - index.md

  - Repositories:
    - mkdocs-a: '!include docs/repos/mkdocs-starter/mkdocs.yml'
    - solutions-delivery-platform: '!include docs/repos/solutions-delivery-platform/mkdocs.yml'
    - UIP-Design-Kit: '!include docs/repos/UIP-Design-Kit/mkdocs.yml'
  - test:
    - Software Factory: '!include docs/repos/booz-allen-software-factory/mkdocs.yml'