site_name: MkDocs Starter
theme:
  name: material
  features: 
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes #to be review
    - navigation.path
    - toc.integrate
    - toc.follow


edit_uri: edit/main/docs/
repo_url: https://github.com/boozallen/mkdocs-yamp-plugin

markdown_extensions:
  - admonition
  - abbr
  - footnotes
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: "docs"
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search: {}
  - yamp:
      # delete docs/repos after build||serve?
      cleanup: false
      # directory within docs dir to add content
      temp_dir: "repos"
      repos:
        # - url: https://github.com/steven-terrana/mkdocs-b
        #   repo_name: "mkdocs-b"
        #   branch: develop
        - url: https://github.com/steven-terrana/mkdocs-a
          repo_name: "mkdocs-a"
        - url: https://bcerdass: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@github.com/boozallen/software-factory
          repo_name: "software-factory"
  - monorepo



extra_css:
 - css/extra.css #to be review

extra: #to be review
  generator: false
  version:
    provider: mike
    default: latest

# Page Tree
nav:
  - Home: 
    - index.md

  - Repositories:
    - Software Factory: '!include ./docs/repos/software-factory/mkdocs.yml'
    - mkdocs-a: '!include ./docs/repos/mkdocs-a/mkdocs.yml'
